modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="gpmod"
version="1.0"
displayName="Gear Progression"
logoFile="examplemod.png"
credits="You guys"
authors="PauseB"
description="""
Add some features enough to make tools your best companion.
"""

[[dependencies.gpmod]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gpmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
